<?php

/**
 * @file
 * Contains main module functionality.
 */

/**
 * Implements hook_menu().
 */
function dynamic_entity_reference_menu() {
  $items = array();
  $items['dynamic_entity_reference/autocomplete/%/%/%/%'] = array(
    'page callback' => 'dynamic_entity_reference_autocomplete',
    'page arguments' => array(2, 3, 4, 5),
    'access callback' => TRUE,
    'file' => 'dynamic_entity_reference.pages.inc',
  );
  return $items;
}
