<?php

/**
 * @file
 * Contains main module functionality.
 */

require_once __DIR__ . '/dynamic_entity_reference.field.inc';

/**
 * Implements hook_menu().
 */
function dynamic_entity_reference_menu() {
  $items = array();
  $items['dynamic_entity_reference/autocomplete'] = array(
    'page callback' => 'dynamic_entity_reference_autocomplete',
    'access callback' => TRUE,
    'file' => 'dynamic_entity_reference.pages.inc',
  );
  return $items;
}
