default:
  image: skpr/php-cli:${PHP_VERSION}-v2-latest
  services:
    - name: mysql:${MYSQL_VERSION}
      alias: mysql

stages:
  - pre
  - build
  - lint
  - test

variables:
  # Configure mysql environment variables (https://hub.docker.com/_/mysql/)
  MYSQL_ROOT_PASSWORD: drupal
  MYSQL_DATABASE: drupal
  MYSQL_USER: drupal
  MYSQL_PASSWORD: drupal
  SIMPLETEST_DB: mysql://drupal:drupal@mysql/drupal
  SIMPLETEST_BASE_URL: http://localhost:8080
  BROWSERTEST_OUTPUT_DIRECTORY: app/sites/default/files
  BROWSERTEST_OUTPUT_FILE: test-output.html
  MINK_DRIVER_ARGS_WEBDRIVER: '["chrome", {"chromeOptions": { "args": [ "--disable-gpu", "--headless" ] } }, "http://chrome:4444/wd/hub" ]'

build app:
  stage: build
  cache:
    key: ${CI_COMMIT_REF_SLUG}-composer
    paths:
      - app/vendor/
  script:
    - cp -r ${CI_PROJECT_DIR} /tmp/${CI_PROJECT_NAME}
    - git clone --depth 1 --branch ${DRUPAL_CORE_CONSTRAINT}.x https://git.drupal.org/project/drupal.git app
    - mv /tmp/${CI_PROJECT_NAME} app/modules/
    - cd app
    - git log -1 --oneline
    - composer install --prefer-dist --no-progress
    - composer require --dev "phpstan/phpstan-deprecation-rules:^1.0"
    - composer show
    - cp modules/${CI_PROJECT_NAME}/.drupalci/* .
    - mkdir -p ${BROWSERTEST_OUTPUT_DIRECTORY}
  artifacts:
    expire_in: 1 hour
    paths:
      - app/composer.lock
      - app/

phpcs:
  stage: lint
  needs: ["build app"]
  script:
    - cd app
    - touch phpcs-report.xml
    - vendor/bin/phpcs
      --standard=vendor/drupal/coder/coder_sniffer/Drupal
      --extensions=php,module,inc,install,test,profile,theme,css,info
      --ignore=*.md
      --report=junit
      --report-file=phpcs-report.xml
      modules/${CI_PROJECT_NAME}
  dependencies:
    - build app
  artifacts:
    when: always
    reports:
      junit: app/phpcs-report.xml

phpstan:
  stage: lint
  needs: ["build app"]
  script:
    - cd app
    - cp modules/${CI_PROJECT_NAME}/phpstan.neon .
    - touch phpstan-report.xml
    - vendor/bin/phpstan analyze
      --memory-limit=-1
      --no-progress
      --error-format=junit
      modules/${CI_PROJECT_NAME}
      > phpstan-report.xml
    - cat phpstan-report.xml
  dependencies:
    - build app
  artifacts:
    when: always
    reports:
      junit: app/phpstan-report.xml

#test unit:
#  needs: ["build app"]
#  stage: test
#  before_script:
#    - cd app
#    - touch phpunit-report-unit.xml
#  script:
#    - vendor/bin/phpunit --configuration ./core/phpunit.xml.dist --log-junit phpunit-report-unit.xml modules/${CI_PROJECT_NAME}/tests/src/Unit/
#  dependencies:
#    - build app
#  artifacts:
#    when: always
#    reports:
#      junit: app/phpunit-report-unit.xml

test kernel:
  needs: ["build app"]
  stage: test
  before_script:
    - cd app
    - touch phpunit-report-kernel.xml
    - ./wait-for-it.sh -s -t 180 mysql:3306 -- echo "MySQL is Ready"
  script:
    - vendor/bin/phpunit --configuration ./core/phpunit.xml.dist --log-junit phpunit-report-kernel.xml modules/${CI_PROJECT_NAME}/tests/src/Kernel/
  dependencies:
    - build app
  artifacts:
    when: always
    reports:
      junit: app/phpunit-report-kernel.xml

test functional:
  needs: ["build app"]
  stage: test
  before_script:
    - cd app
    - touch phpunit-report-functional.xml
    - php -S 0.0.0.0:8080 .ht.router.php >> http.log 2>&1 &
    - ./wait-for-it.sh -s -t 180 mysql:3306 -- echo "MySQL is Ready"
  script:
    - vendor/bin/phpunit --configuration ./core/phpunit.xml.dist --log-junit phpunit-report-functional.xml modules/${CI_PROJECT_NAME}/tests/src/Functional/
  dependencies:
    - build app
  artifacts:
    when: always
    reports:
      junit: app/phpunit-report-functional.xml
    paths:
      - app/http.log
      - app/sites/simpletest/browser_output/

test functional javascript:
  needs: ["build app"]
  stage: test
  image: skpr/php-cli:${PHP_VERSION}-v2-latest
  services:
    - name: mysql:${MYSQL_VERSION}
      alias: mysql
    - name: selenium/standalone-chrome:latest
      alias: chrome
  before_script:
    - cd app
    - touch phpunit-report-functional-javascript.xml
    - php -S 0.0.0.0:8080 .ht.router.php >> http.log 2>&1 &
    - ./wait-for-it.sh -s -t 180 mysql:3306 -- echo "MySQL is Ready"
  script:
    - vendor/bin/phpunit --configuration ./core/phpunit.xml.dist --log-junit phpunit-report-functional-javascript.xml modules/${CI_PROJECT_NAME}/tests/src/FunctionalJavascript/
  dependencies:
    - build app
  artifacts:
    when: always
    reports:
      junit: app/phpunit-report-functional-javascript.xml
    paths:
      - app/http.log
      - app/sites/simpletest/browser_output/
