<?php

/**
 * Implements hook_entity_type_alter().
 */
function dynamic_entity_reference_275136_entity_type_alter(array &$entity_types) {
  $r = new ReflectionClass('Drupal\Core\Entity\EntityType');
  $p = $r->getProperty('base_table');
  $p->setAccessible(TRUE);
  foreach (['entity_test_cache', 'entity_test_constraint_violation', 'entity_test_default_access', 'entity_test_label', 'entity_test_label_callback', 'entity_test_no_label', 'entity_test_view_builder'] as $n) {
    if (isset($entity_types[$n])) {
      $p->setValue($entity_types[$n], $n);
    }
  }
}
