<?php

/**
 * @file
 * Module file for dynamic_entity_reference_entity_test.
 */

use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\Core\StringTranslation\TranslatableMarkup;

/**
 * Implements hook_entity_base_field_info().
 */
function dynamic_entity_reference_entity_test_entity_base_field_info(EntityTypeInterface $entity_type) {
  $fields = [];
  // 'entity_test' with no data table and 'entity_test_mul' is with data table.
  if ($entity_type->id() == 'entity_test' || $entity_type->id() == 'entity_test_mul') {
    $fields['dynamic_references'] = BaseFieldDefinition::create('dynamic_entity_reference')
      ->setLabel((string) new TranslatableMarkup('References'))
      ->setDescription((string) new TranslatableMarkup('Reference another entity.'))
      ->setRequired(FALSE)
      ->setCardinality(\Drupal::state()->get('dynamic_entity_reference_entity_test_cardinality', 1))
      ->setDisplayOptions('form', [
        'type' => 'dynamic_entity_reference_default',
        'weight' => 10,
      ])
      ->setDisplayOptions('view', [
        'label' => 'above',
        'type' => 'dynamic_entity_reference_label',
        'weight' => 10,
      ])
      ->setDisplayConfigurable('form', TRUE)
      ->setDisplayConfigurable('view', TRUE);
    if (\Drupal::state()->get('dynamic_entity_reference_entity_test_exclude', '') == 'entity_test') {
      $fields['dynamic_references']
        ->setSettings([
          'exclude_entity_types' => FALSE,
          'entity_type_ids' => [
            'entity_test_mul' => 'entity_test_mul',
          ],
          'entity_test_mul' => [
            'handler' => "default:entity_test_mul",
            'handler_settings' => [],
          ],
        ]);
    }
    else {
      $fields['dynamic_references']
      ->setSettings([
        'exclude_entity_types' => FALSE,
        'entity_type_ids' => [
          'entity_test' => 'entity_test',
          'entity_test_mul' => 'entity_test_mul',
        ],
        'entity_test' => [
          'handler' => "default:entity_test",
          'handler_settings' => [],
        ],
        'entity_test_mul' => [
          'handler' => "default:entity_test_mul",
          'handler_settings' => [],
        ],
      ]);
    }

  }

  return $fields;
}
